### PR TITLE
Renames most occurances of grabber to claw

### PR DESCRIPTION
**Pull request by tails618**
This PR changes most instances of grabber to claw. There has been lengthy discussion about the term grabber vs gripper. However, I propose that we switch to claw. This is based on the fact that there is a precedent for using the term claw, notably from both Nick (see figure 1) and Jay (see figure 2).

image
Figure 1

image
Figure 2

Claw also uses less characters and syllables, thus being more efficient to type and say (and uses less storage on the NI roboRIO 2.0). Additionally, claw is a way to resolve the argument about gripper vs grabber without having to pick sides.

Lastly, Jay made it clear that he did not believe that I would create this PR (see figure 3). I simply cannot let that heinous lack of faith in my work ethic go unaddressed.

image
Figure 3

Your move, Jay.

### CODE REVIEW

**Review by Panda8188 — APPROVED** [review]
I am Sid and I WHOLEHEARTEDLY approve this PR.


THECLAAAAAAAAAAAAAAAW

**Review by balghane — CHANGES_REQUESTED** [review]
Should really be "theClaaaaaww"

**Comment by tails618** [comment]
> Should really be "theClaaaaaww"

Fixed 👍

**Review by avakimc — APPROVED** [review]
My name is Ava Kim Cohen and I especially approve this PR 👍

**Review by Panda8188 — APPROVED** [review]
I am Sid and i APPROVE THESE SPECTACULARLY AMAZINGLY STUNNINGLY GENIUS CHANGES

theCLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW

**Pull request closed without merging**
