### PR TITLE
Change Cardinal Directions Buttons to 45 Degree Rotations

### PR DESCRIPTION
**Pull request by avakimc**
* created convertCardinalDirections() method to convert the povAngleDeg into 45 degree angle rotations for left and right d-pad buttons

### CODE REVIEW

**Review by balghane — APPROVED** [review]

**Review by balghane — CHANGES_REQUESTED** [review]
This merge undid some other changes that we actually wanted

**Review by tails618 — APPROVED** [review]

**Review by balghane — APPROVED** [review]

**Pull request merged**
